# Generated by Django 4.2.1 on 2023-06-17 09:51

import base.id_generator.generator
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(default=base.id_generator.generator.DefaultIdGenerator.next_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('mobile', models.CharField(max_length=32, unique=True, verbose_name='手机号码')),
                ('mail', models.CharField(default=None, max_length=128, null=True, unique=True, verbose_name='邮箱')),
                ('mail_active', models.BooleanField(default=False, verbose_name='邮箱验证状态')),
                ('mail_active_at', models.DateTimeField(null=True, verbose_name='邮箱验证时间')),
                ('identity', models.SmallIntegerField(choices=[('0', '管理员'), ('1', '普通用户')], default='1', verbose_name='身份, 0管理员, 1普通用户')),
                ('status', models.SmallIntegerField(choices=[('0', '启用'), ('1', '禁用')], default='0', verbose_name='状态, 0启用, 1禁用')),
                ('last_login_at', models.DateTimeField(null=True, verbose_name='上次登陆时间')),
                ('created', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated', to=settings.AUTH_USER_MODEL, verbose_name='上次修改人')),
            ],
            options={
                'db_table': 'user_user',
            },
        ),
    ]
