# Generated by Django 4.2.1 on 2023-06-17 12:38

import base.id_generator.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(default=base.id_generator.generator.DefaultIdGenerator.next_id, primary_key=True, serialize=False),
        ),
    ]
