# Generated by Django 4.2.1 on 2023-06-17 12:38

import base.id_generator.generator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigIntegerField(default=base.id_generator.generator.DefaultIdGenerator.next_id, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(verbose_name='库存数量')),
                ('product_code', models.IntegerField()),
                ('warehouse', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'inventory_inventory',
            },
        ),
    ]
