from ..env import env

ALIYUN_SMS_ACCESS_KEY = env.str("ALIYUN_SMS_ACCESS_EKY")
ALIYUN_SMS_SECRET = env.str("ALIYUN_SMS_SECRET")
ALIYUN_SMS_REGION = env.str("ALIYUN_SMS_REGION")
ALIYUN_SMS_DOMAIN = env.str("ALIYUN_SMS_DOMAIN")
ALIYUN_SMS_SIGN_NAME = env.str("ALIYUN_SMS_SING_NAME")
ALIYUN_SMS_TEMPLATE_CODE = env.str("ALIYUN_SMS_TEMPLATE_CODE")

SMS_TEST_PHONES = env.list("SMS_TEST_PHONES")
